# Generated by Django 5.0.2 on 2024-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'receptionist')], primary_key=True, serialize=False)),
            ],
            
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_type',
            field=models.ManyToManyField(related_name='user_profile_type', to='users.profiletype'),
        ),
    ]
