# Generated by Django 5.0.2 on 2024-02-29 07:53

from django.db import migrations, models
from users.models import CustomUser, ProfileType
from django.contrib.auth import get_user_model

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profiletype_remove_customuser_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='profile_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'receptionist')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
