# Generated by Django 5.0.2 on 2024-07-09 22:03

from django.db import migrations, connection

def create_unaccent_extension(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('CREATE EXTENSION IF NOT EXISTS unaccent')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiletype_profile_type_alter_profiletype_id'),
    ]

    operations = [
        migrations.RunPython(create_unaccent_extension),
    ]
