# Generated by Django 5.0.2 on 2024-08-22 17:09

from django.db import migrations, models
from users.models import CustomUser, ProfileType
from django.contrib.auth import get_user_model

def create_profiles_and_users(apps, schema_editor):
    exists = ProfileType.objects.filter(profile_type=1).exists()
    if not exists:
        ProfileType.objects.create(profile_type=ProfileType.ADMIN)

    exists = ProfileType.objects.filter(profile_type=2).exists()
    if not exists:
        ProfileType.objects.create(profile_type=ProfileType.RECEPCIONIST)
        
    exists = CustomUser.objects.filter(email='casani@recepcionista.com').exists()
    if not exists:
        User = get_user_model()
        receptionist_profile_type = ProfileType.objects.get(profile_type=ProfileType.RECEPCIONIST)
        user = User.objects.create_user(
            first_name='Recepcionista',
            last_name='Casani',
            email='casani@recepcionista.com',
            password='casani123',
        )
        user.profile_type.add(receptionist_profile_type)  # Use add() para adicionar o perfil ao usuário
        user.save()
        
    exists = CustomUser.objects.filter(email='casani@admin.com').exists()
    if not exists:
        User = get_user_model()
        admin_profile_type = ProfileType.objects.get(profile_type=ProfileType.ADMIN)
        user = User.objects.create_superuser(
            first_name='Admin',
            last_name='Casani',
            email='casani@admin.com',
            password='casani123',
            is_superuser = True,
        )
        user.profile_type.add(admin_profile_type)
        user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_photo'),
    ]

    operations = [
         migrations.RunPython(create_profiles_and_users)
    ]
