version: "3.8"
services:
  db:
    image: postgres
    container_name: app_db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  app:
    container_name: app_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/src/
