# Generated by Django 5.0.2 on 2024-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
