# Generated by Django 5.0.2 on 2024-05-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('profissao', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('historico', models.TextField(blank=True, null=True)),
                ('profissao2', models.CharField(blank=True, max_length=255, null=True)),
                ('anos', models.IntegerField(blank=True, null=True)),
                ('paciente1', models.CharField(blank=True, max_length=255, null=True)),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('queixas', models.TextField(blank=True, null=True)),
                ('antecedentes1', models.TextField(blank=True, null=True)),
                ('antecedentes2', models.TextField(blank=True, null=True)),
                ('antecedentes3', models.TextField(blank=True, null=True)),
                ('situacao_social', models.TextField(blank=True, null=True)),
                ('idade2', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aspectos', models.TextField(blank=True, null=True)),
                ('ritmo', models.CharField(blank=True, max_length=50, null=True)),
                ('bulhas', models.CharField(blank=True, max_length=50, null=True)),
                ('sopros', models.CharField(blank=True, max_length=50, null=True)),
                ('pressao', models.CharField(blank=True, max_length=50, null=True)),
                ('pulso', models.CharField(blank=True, max_length=50, null=True)),
                ('aparelho_respiratorio', models.CharField(blank=True, max_length=50, null=True)),
                ('abdomem', models.CharField(blank=True, max_length=50, null=True)),
                ('tireoide', models.CharField(blank=True, max_length=50, null=True)),
                ('hipotese_diagnostico', models.TextField(blank=True, null=True)),
                ('idade3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
