# Generated by Django 5.0.2 on 2024-05-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='paciente',
            field=models.CharField(max_length=255),
        ),
    ]
