# Generated by Django 5.0.2 on 2024-05-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0002_alter_importdata_altura_alter_importdata_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='abdomem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='aparelho_respiratorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='bulhas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='ritmo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='sopros',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='tireoide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
