# Generated by Django 5.0.2 on 2024-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0003_alter_importdata_abdomem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
