# Generated by Django 5.0.2 on 2024-07-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0004_alter_importdata_altura_alter_importdata_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdata',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
