# Generated by Django 5.0.2 on 2024-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0005_importdata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importdata',
            name='paciente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
