# Generated by Django 5.0.2 on 2024-07-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0006_alter_importdata_endereco_alter_importdata_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
