from django.db import models


class Pacientes(models.Model):
    paciente = models.CharField(max_length=255, null=True, blank=True)
    endereco = models.CharField(max_length=255, null=True, blank=True)
    cidade = models.CharField(max_length=100, null=True, blank=True)
    profissao = models.CharField(max_length=255, null=True, blank=True)
    telefone = models.CharField(max_length=50, null=True, blank=True)
    data_nascimento = models.DateField(null=True, blank=True)
    sexo = models.CharField(max_length=10, null=True, blank=True)
    cor = models.CharField(max_length=50, null=True, blank=True)
    observacoes = models.TextField(null=True, blank=True)
    historico = models.TextField(null=True, blank=True)
    profissao2 = models.CharField(max_length=255, null=True, blank=True)
    anos = models.IntegerField(null=True, blank=True)
    paciente1 = models.CharField(max_length=255, null=True, blank=True)
    data_consulta = models.DateField(null=True, blank=True)
    queixas = models.TextField(null=True, blank=True)
    antecedentes1 = models.TextField(null=True, blank=True)
    antecedentes2 = models.TextField(null=True, blank=True)
    antecedentes3 = models.TextField(null=True, blank=True)
    situacao_social = models.TextField(null=True, blank=True)
    idade2 = models.IntegerField(null=True, blank=True)
    peso = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    altura = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    aspectos = models.TextField(null=True, blank=True)
    ritmo = models.CharField(max_length=100, null=True, blank=True)
    bulhas = models.CharField(max_length=100, null=True, blank=True)
    sopros = models.CharField(max_length=100, null=True, blank=True)
    pressao = models.CharField(max_length=50, null=True, blank=True)
    pulso = models.CharField(max_length=50, null=True, blank=True)
    aparelho_respiratorio = models.CharField(max_length=100, null=True, blank=True)
    abdomem = models.CharField(max_length=100, null=True, blank=True)
    tireoide = models.CharField(max_length=100, null=True, blank=True)
    hipotese_diagnostico = models.TextField(null=True, blank=True)
    idade3 = models.IntegerField(null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)